version: '3.4'

volumes:
  datafiles:

services:

  database:
    image: mysql:8.0.22
    ports:
      - "1212:3306"
    volumes:
      - datafiles:/var/lib/mysql
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Olivier7
      MYSQL_USER: root
      MYSQL_PASSWORD: Olivier7
      MYSQL_DATABASE: golfmaxdb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5000:8800"
    restart: always
    environment:
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development