version: '3.1'

services:
  db:
    image: mysql:latest
    ports:
      - "3316:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Olivier7
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=golfmaxdb
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always

  golfmaxwebapi:
    image: golfmax/webapi:runtime
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

volumes:
  dbdata: